global using Ardalis.Specification;
global using static System.ArgumentException;
global using static System.ArgumentNullException;
global using static System.ArgumentOutOfRangeException;
global using SmartTimetableGenerator.Domain.Common.Base;
global using SmartTimetableGenerator.Domain.Common.EventualConsistency;
global using SmartTimetableGenerator.Domain.Common.Interfaces;
global using ErrorOr;
global using Vogen;
global using SmartTimetableGenerator.Domain.Common.Calendar;
global using SmartTimetableGenerator.Domain.Common.Rules;
